FROM python:buster

COPY requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

COPY *.py /app/
WORKDIR /app

ENTRYPOINT ["celery", "-A", "celery_tasks", "worker", "--loglevel=debug"]