apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbit-mq
  name: rabbit-mq-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
         app: rabbit-mq
    spec:
      containers:
      - image: rabbitmq:latest
        imagePullPolicy: Never
        name: rabbit-mq
        ports:
        - containerPort: 5672
      restartPolicy: Always
      hostname: rabbit-mq

---

apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-svc
spec:
  selector:
    app: rabbit-mq
  ports:
  - port: 5672