apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
         app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-config
          - mountPath: /statics
            name: statics
      restartPolicy: Always
      hostname: nginx
      volumes:
        - name: nginx-config
          hostPath:
            path: /c/Users/Grześ/Desktop/projekt/reddit.cl/nginx
        - name: statics
          hostPath:
            path: /c/Users/Grześ/Desktop/projekt/reddit.cl/src/main/webapp/static
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80