apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reddit-cl
  name: reddit-cl-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-cl
  template:
    metadata:
      labels:
         app: reddit-cl
    spec:
      containers:
      - image: reddit_cl:latest
        imagePullPolicy: Never
        name: reddit-cl
        ports:
        - containerPort: 8080
      restartPolicy: Always
      hostname: reddit-cl

---

apiVersion: v1
kind: Service
metadata:
  name: reddit-cl-svc
spec:
  type: NodePort
  selector:
    app: reddit-cl
  ports:
  - port: 8080